import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/sharedComponents/Footer";
import Navbar from "@/components/sharedComponents/Navbar";
import AuthProvider from '../services/AuthProvider'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    default:'Car Doctor',
    template:'%s | Car Doctor'
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <AuthProvider>
      <body className={`${inter.className} max-w-7xl`}>
        <Navbar></Navbar>

        {children}
        <Footer></Footer>
      </body>
      </AuthProvider>
    </html>
  );
}
